### ISSUE TITLE
Does it support newer VSCode versions?

### ISSUE THREAD

**Issue by gsdeveloper** [Divlo/vscode-styled-jsx#37]
### Question
I'm getting an error when trying to install, currently there's no support for newer VS Code versions? 
> "Unable to install 'divlo.vscode-styled-jsx-languageserver' extension because it is not  compatible with the current  version of VS Code (version 1.48.2)"

**Comment by Divlo** [comment]
Hey 👋,

Yes it supports newer VSCode versions, since it supports versions above `1.50`, so we don't support older versions of `1.50`.
https://github.com/Divlo/vscode-styled-jsx/blob/80d2de43432a9bbc1fdd659f2167e3782a739495/vscode-styled-jsx-languageserver/package.json#L18

Currently I'm running the latest version of VSCode (`1.53.2`) and it is running fine! 
Please upgrade your VSCode, and if you like the extension and it is working, feel free to give the repo a start, thank you! :smile:
